language: c
sudo: false
install: true

addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.7
    packages:
    - libstdc++6
    - libllvm3.7
    - llvm-3.7-runtime 
    - llvm-3.7

before_script:
  - mkdir bin
  - wget https://github.com/ocaml/opam/releases/download/1.2.2/opam-1.2.2-x86_64-Linux -O $PWD/bin/opam
  - export PATH=$PATH:$PWD/bin/
  - chmod +x $PWD/bin/opam

script: bash -ex .travis-ocaml.sh
env:
  - DEPS="llvm core core_extended sedlex" BUILD_CMD="make"